name: build

on:
  push:
  pull_request:
  schedule:
  - cron: "55 14 * * 5"  # Run at a random time weekly

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7, 3.8]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup conda and dependencies
      run: |
        git clone --depth 5 https://github.com/salilab/rmf.git ~/rmf
        tools/setup_travis.sh ~/conda ${{ matrix.python-version }}
        rm -f ${CONDA_PREFIX}/lib/libimp_npctransport.so* ${CONDA_PREFIX}/lib/_IMP_npctransport.so
    - name: Test
      run: |
        export IMP_TMP_DIR=/tmp
        source ~/conda/bin/activate python${{ matrix.python-version }}
        # Use same C/C++ compiler as conda
        source ${CONDA_PREFIX}/etc/conda/activate.d/activate-gcc_linux-64.sh
        source ${CONDA_PREFIX}/etc/conda/activate.d/activate-gxx_linux-64.sh
        mkdir build && cd build
        if test "${{ matrix.python-version }}" = "2.7" ; then PY2=on; else PY2=off; fi
        cmake .. -DIMP_DIR=${CONDA_PREFIX}/lib/cmake/IMP -DUSE_PYTHON2=${PY2} -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage" -DAVROCPP_INCLUDE_PATH=~/rmf/src/avrocpp/api
        make
        ./setup_environment.sh ../test/nosetests --with-coverage --cover-branches -e 'probabilistic' -e 'test_protobuf_installed' -e 'add_test_sites' ../test/test_*.py ../test/medium_test_*.py test/*/*.py > /dev/null
    - name: Upload coverage to codecov
      run: |
        bash <(curl -s https://codecov.io/bash)
